# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('message', 'message'),
        ('protocols', 'protocols')
    ],
    hiddenimports=[
        'zeroconf',
        'zeroconf.utils',
        'zeroconf._services',
        'zeroconf._services.types',
        'zeroconf._services.info',
        'zeroconf._core',
        'zeroconf._engine',
        'zeroconf._listener',
        'zeroconf._utils.asyncio',
        'zeroconf._utils.net',
        'zeroconf._utils.ipdress',
        'zeroconf._utils',
        'ifaddr',
        'typing_extensions',
        'async_timeout',
        'asyncio',
        'asyncio.base_events',
        'asyncio.coroutines',
        'asyncio.events',
        'collections.abc',
        'multiprocessing',
        'multiprocessing.pool',
        'multiprocessing.connection',
        'multiprocessing.shared_memory',
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'uuid',
        'socket',
        'threading',
        'time',
        'typing'
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_no_private_assemblies=False,
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Net_Test',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
